import { describe, it, expect } from 'vitest';
import { createHash, createPrivateKey, generateKeyPairSync, sign as edSign } from 'node:crypto';
import { readFileSync } from 'node:fs';

import {
  SIG_PAYLOAD_FORMAT,
  canonicalizeAudit,
  deriveKeyId,
  buildSigningPayload,
  verifyIssuerSignature,
  computeAuditHashV2,
  verifyAuditReport,
  type IssuerSignature,
} from '@panguard-ai/core/signing/index.js';

/**
 * The PUBLISHED issuer public key from
 * packages/website/public/.well-known/panguard-signing-key.json. deriveKeyId
 * MUST reproduce the published key_id from this PEM — a public trust promise.
 */
const PUBLISHED_PEM =
  '-----BEGIN PUBLIC KEY-----\n' +
  'MCowBQYDK2VwAyEAE8yWwjJ9K3FUibtTZq640dHJVEGw26AM8NiM749fzqU=\n' +
  '-----END PUBLIC KEY-----\n';
const PUBLISHED_KEY_ID = 'pgk1-621b5f58dbfa5e2c';

/**
 * CROSS-REPO FIXTURE: generated by running the PRIVATE issuer code
 * (@panguard/migrator computeAuditHash + signHashWithIssuer) with a throwaway
 * keypair. If the public canonicalizeAudit / payload rebuild ever drifts from
 * the issuer side, these tests break — that is their job.
 */
const FIXTURE_URL = new URL('./fixtures/issuer-signed-report.fixture.json', import.meta.url);
const FIXTURE_KEY_ID = 'pgk1-0f2b480ffe2eaacc';

function loadFixture(): Record<string, unknown> {
  return JSON.parse(readFileSync(FIXTURE_URL, 'utf8')) as Record<string, unknown>;
}

function fixtureIntegrity(doc: Record<string, unknown>): {
  sha256: string;
  issuer_signature: IssuerSignature;
} {
  return doc['integrity'] as { sha256: string; issuer_signature: IssuerSignature };
}

interface LocalSigner {
  privatePem: string;
  publicPem: string;
  keyId: string;
}

function makeSigner(): LocalSigner {
  const { privateKey, publicKey } = generateKeyPairSync('ed25519');
  const publicPem = publicKey.export({ type: 'spki', format: 'pem' }).toString();
  return {
    privatePem: privateKey.export({ type: 'pkcs8', format: 'pem' }).toString(),
    publicPem,
    keyId: deriveKeyId(publicPem),
  };
}

/** Local signer mirroring the private signHashWithIssuer semantics exactly. */
function localSign(
  sha256: string,
  binding: { kind: string; framework: string; jurisdiction: string },
  signer: LocalSigner,
  signedAt = '2026-08-18T00:00:00.000Z'
): IssuerSignature {
  const payload = buildSigningPayload(sha256, binding, signer.keyId, signedAt);
  return {
    scheme: 'issuer',
    payload_format: SIG_PAYLOAD_FORMAT,
    alg: 'Ed25519',
    key_id: signer.keyId,
    issuer: 'Local Test Issuer',
    public_key_pem: signer.publicPem,
    signature_b64: edSign(
      null,
      Buffer.from(payload, 'utf-8'),
      createPrivateKey(signer.privatePem)
    ).toString('base64'),
    signed_at: signedAt,
    kind: binding.kind,
    framework: binding.framework,
    jurisdiction: binding.jurisdiction,
  };
}

describe('deriveKeyId', () => {
  it('reproduces the published key_id from the published PEM', () => {
    expect(deriveKeyId(PUBLISHED_PEM)).toBe(PUBLISHED_KEY_ID);
  });

  it('reproduces the fixture key_id from the embedded public key', () => {
    const sig = fixtureIntegrity(loadFixture()).issuer_signature;
    expect(deriveKeyId(sig.public_key_pem)).toBe(FIXTURE_KEY_ID);
  });

  it('throws on garbage input', () => {
    expect(() => deriveKeyId('not a pem')).toThrow();
  });
});

describe('canonicalizeAudit — parity with the issuer-side canonicalize', () => {
  it('is independent of object key insertion order at every depth', () => {
    const a = { outer: { b: 2, a: 1 }, list: [{ y: 1, x: 2 }] };
    const b = { list: [{ x: 2, y: 1 }], outer: { a: 1, b: 2 } };
    expect(canonicalizeAudit(a)).toBe(canonicalizeAudit(b));
  });

  it('preserves array order', () => {
    expect(canonicalizeAudit([1, 2])).not.toBe(canonicalizeAudit([2, 1]));
  });

  it('drops undefined-valued keys (issuer convention)', () => {
    expect(canonicalizeAudit({ a: 1, b: undefined })).toBe(canonicalizeAudit({ a: 1 }));
  });
});

describe('computeAuditHashV2 — cross-repo parity', () => {
  it('reproduces the integrity.sha256 the PRIVATE issuer code computed', () => {
    const doc = loadFixture();
    expect(computeAuditHashV2(doc)).toBe(fixtureIntegrity(doc).sha256);
  });

  it('returns null for a report without the v2 hashSchema marker (fail closed)', () => {
    const doc = loadFixture();
    const metadata = { ...(doc['metadata'] as Record<string, unknown>) };
    delete metadata['hashSchema'];
    expect(computeAuditHashV2({ ...doc, metadata })).toBeNull();
  });

  it('changes when any NESTED body field changes', () => {
    const doc = loadFixture();
    const baseline = computeAuditHashV2(doc);
    const tampered = JSON.parse(JSON.stringify(doc)) as Record<string, unknown>;
    (tampered['findings'] as Array<Record<string, unknown>>)[0]!['evidence'] = 'edited';
    expect(computeAuditHashV2(tampered)).not.toBe(baseline);
  });
});

describe('verifyIssuerSignature', () => {
  it('accepts the fixture signature produced by the private issuer code', () => {
    const { sha256, issuer_signature } = fixtureIntegrity(loadFixture());
    expect(verifyIssuerSignature(sha256, issuer_signature).valid).toBe(true);
  });

  it('rejects an unsupported payload format', () => {
    const { sha256, issuer_signature } = fixtureIntegrity(loadFixture());
    const outcome = verifyIssuerSignature(sha256, {
      ...issuer_signature,
      payload_format: 'PGA-SIG-V9' as typeof SIG_PAYLOAD_FORMAT,
    });
    expect(outcome.valid).toBe(false);
    expect(outcome.reason).toBe('unsupported-payload-format');
  });

  it('rejects when the embedded key does not hash to the claimed key_id', () => {
    const { sha256, issuer_signature } = fixtureIntegrity(loadFixture());
    const outcome = verifyIssuerSignature(sha256, {
      ...issuer_signature,
      key_id: 'pgk1-0000000000000000',
    });
    expect(outcome.valid).toBe(false);
    expect(outcome.reason).toBe('embedded-key-id-mismatch');
  });

  it('rejects an unreadable embedded public key', () => {
    const { sha256, issuer_signature } = fixtureIntegrity(loadFixture());
    const outcome = verifyIssuerSignature(sha256, {
      ...issuer_signature,
      public_key_pem: 'not a pem',
    });
    expect(outcome.valid).toBe(false);
    expect(outcome.reason).toBe('embedded-key-unreadable');
  });

  it('rejects when the binding context was altered (anti-replay)', () => {
    const { sha256, issuer_signature } = fixtureIntegrity(loadFixture());
    const outcome = verifyIssuerSignature(sha256, { ...issuer_signature, jurisdiction: 'eu' });
    expect(outcome.valid).toBe(false);
    expect(outcome.reason).toBe('bad-signature');
  });

  it('rejects when signed_at was altered (payload-bound timestamp)', () => {
    const { sha256, issuer_signature } = fixtureIntegrity(loadFixture());
    const outcome = verifyIssuerSignature(sha256, {
      ...issuer_signature,
      signed_at: '2026-01-01T00:00:00.000Z',
    });
    expect(outcome.valid).toBe(false);
    expect(outcome.reason).toBe('bad-signature');
  });
});

describe('verifyAuditReport — full offline flow', () => {
  it('verifies the cross-repo fixture end-to-end when its key_id is trusted', () => {
    const result = verifyAuditReport(loadFixture(), { trustedKeyIds: [FIXTURE_KEY_ID] });
    expect(result.ok).toBe(true);
    expect(result.status).toBe('verified-issuer');
    expect(result.keyId).toBe(FIXTURE_KEY_ID);
    expect(result.issuer).toBe('Fixture Issuer Co.');
    expect(result.jurisdiction).toBe('us');
    expect(result.trustedKey).toBe(true);
  });

  it('an explicit --expect-key pin overrides trust-list membership', () => {
    const result = verifyAuditReport(loadFixture(), {
      trustedKeyIds: [PUBLISHED_KEY_ID],
      expectKeyId: FIXTURE_KEY_ID,
    });
    expect(result.ok).toBe(true);
    expect(result.trustedKey).toBe(false);
  });

  it('rejects an issuer key_id that is neither pinned nor on the trust list', () => {
    const result = verifyAuditReport(loadFixture(), { trustedKeyIds: [PUBLISHED_KEY_ID] });
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('untrusted-key-id');
    expect(result.keyId).toBe(FIXTURE_KEY_ID);
  });

  it('rejects a wrong --expect-key pin', () => {
    const result = verifyAuditReport(loadFixture(), {
      trustedKeyIds: [FIXTURE_KEY_ID],
      expectKeyId: 'pgk1-0000000000000000',
    });
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('expect-key-mismatch');
  });

  it('detects nested body tampering via the recomputed hash', () => {
    const tampered = JSON.parse(JSON.stringify(loadFixture())) as Record<string, unknown>;
    (tampered['findings'] as Array<Record<string, unknown>>)[0]!['severity'] = 'info';
    const result = verifyAuditReport(tampered, { trustedKeyIds: [FIXTURE_KEY_ID] });
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('hash-mismatch');
  });

  it('fails closed on a v2 report stripped of its hashSchema marker (downgrade)', () => {
    const doc = loadFixture();
    const metadata = { ...(doc['metadata'] as Record<string, unknown>) };
    delete metadata['hashSchema'];
    const result = verifyAuditReport({ ...doc, metadata }, { trustedKeyIds: [FIXTURE_KEY_ID] });
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('legacy-hash-schema');
  });

  it('flags scheme=issuer without a signature block', () => {
    const doc = loadFixture();
    const integrity = { ...(doc['integrity'] as Record<string, unknown>) };
    delete integrity['issuer_signature'];
    const result = verifyAuditReport({ ...doc, integrity }, { trustedKeyIds: [FIXTURE_KEY_ID] });
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('missing-issuer-signature');
  });

  it('accepts a locally signed report (payload build parity with the issuer signer)', () => {
    const signer = makeSigner();
    const doc = JSON.parse(JSON.stringify(loadFixture())) as Record<string, unknown>;
    const { integrity: _integrity, ...body } = doc;
    const sha = computeAuditHashV2(body as Record<string, unknown>);
    expect(sha).not.toBeNull();
    const sig = localSign(
      sha as string,
      { kind: 'report', framework: 'us-financial-services', jurisdiction: 'us' },
      signer
    );
    const signed = {
      ...body,
      integrity: {
        sha256: sha,
        signature_scheme: 'issuer',
        key_id: sig.key_id,
        issuer_signature: sig,
      },
    };
    const result = verifyAuditReport(signed, { trustedKeyIds: [signer.keyId] });
    expect(result.ok).toBe(true);
    expect(result.status).toBe('verified-issuer');
  });

  it('reports hash-only for an unsigned v2 report and fails an --expect-key demand on it', () => {
    const doc = JSON.parse(JSON.stringify(loadFixture())) as Record<string, unknown>;
    const { integrity: _integrity, ...body } = doc;
    const sha = computeAuditHashV2(body as Record<string, unknown>) as string;
    const unsigned = {
      ...body,
      integrity: { sha256: sha, signature_scheme: 'none', unsigned_reason: 'no_issuer_key' },
    };
    const plain = verifyAuditReport(unsigned, { trustedKeyIds: [PUBLISHED_KEY_ID] });
    expect(plain.ok).toBe(true);
    expect(plain.status).toBe('hash-only-unsigned');
    const pinned = verifyAuditReport(unsigned, {
      trustedKeyIds: [PUBLISHED_KEY_ID],
      expectKeyId: PUBLISHED_KEY_ID,
    });
    expect(pinned.ok).toBe(false);
    expect(pinned.reason).toBe('expected-key-but-not-issuer-signed');
  });

  it('labels a server-signed v2 report hash-only (offline server key not yet available)', () => {
    const doc = JSON.parse(JSON.stringify(loadFixture())) as Record<string, unknown>;
    const { integrity: _integrity, ...body } = doc;
    const sha = computeAuditHashV2(body as Record<string, unknown>) as string;
    const serverSigned = {
      ...body,
      integrity: { sha256: sha, signature_scheme: 'server', ed25519_jws: 'x.y.z' },
    };
    const result = verifyAuditReport(serverSigned, { trustedKeyIds: [PUBLISHED_KEY_ID] });
    expect(result.ok).toBe(true);
    expect(result.status).toBe('hash-only-server');
  });

  it('recognizes a guard evidence pack and says so instead of a generic failure', () => {
    const result = verifyAuditReport(
      { kind: 'panguard.evidence-pack', version: '1.2', attestation: {} },
      { trustedKeyIds: [PUBLISHED_KEY_ID] }
    );
    expect(result.ok).toBe(false);
    expect(result.reason).toBe('not-an-audit-report');
    expect(result.detail).toContain('evidence pack');
  });

  it('fixture sha256 sanity: stated hash is a 64-char sha256 hex', () => {
    const { sha256 } = fixtureIntegrity(loadFixture());
    expect(sha256).toMatch(/^[0-9a-f]{64}$/);
    expect(createHash('sha256').update('x').digest('hex')).toHaveLength(64);
  });
});
