import { describe, it, expect, beforeEach, afterEach } from 'vitest';
import { mkdtempSync, readFileSync, writeFileSync, rmSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { join } from 'node:path';

import { computeAuditHashV2 } from '@panguard-ai/core';

import {
  TRUSTED_ISSUER_KEY_IDS,
  reportCommand,
  runReportSignVerify,
} from '../src/cli/commands/report-sign.js';

const PUBLISHED_KEY_ID = 'pgk1-621b5f58dbfa5e2c';
const FIXTURE_KEY_ID = 'pgk1-0f2b480ffe2eaacc';

/** Cross-repo fixture generated by the PRIVATE issuer code (see core tests). */
const FIXTURE_URL = new URL(
  '../../core/tests/fixtures/issuer-signed-report.fixture.json',
  import.meta.url
);

interface CapturedIo {
  out: string[];
  err: string[];
  io: { out: (line: string) => void; err: (line: string) => void };
}

function captureIo(): CapturedIo {
  const out: string[] = [];
  const err: string[] = [];
  return {
    out,
    err,
    io: { out: (line: string) => out.push(line), err: (line: string) => err.push(line) },
  };
}

describe('pga report sign verify (CLI)', () => {
  let dir: string;

  beforeEach(() => {
    dir = mkdtempSync(join(tmpdir(), 'pga-report-verify-'));
  });

  afterEach(() => {
    rmSync(dir, { recursive: true, force: true });
  });

  function fixtureDoc(): Record<string, unknown> {
    return JSON.parse(readFileSync(FIXTURE_URL, 'utf8')) as Record<string, unknown>;
  }

  function writeDoc(doc: Record<string, unknown>, name = 'report.json'): string {
    const file = join(dir, name);
    writeFileSync(file, JSON.stringify(doc, null, 2));
    return file;
  }

  describe('trust store', () => {
    it('bundles the published issuer key_id', () => {
      expect(TRUSTED_ISSUER_KEY_IDS).toContain(PUBLISHED_KEY_ID);
    });
  });

  it('verifies the issuer-signed fixture with an explicit --expect-key pin (exit 0)', async () => {
    const file = writeDoc(fixtureDoc());
    const { io, out } = captureIo();

    const code = await runReportSignVerify(file, { expectKey: FIXTURE_KEY_ID }, io);

    expect(code).toBe(0);
    const text = out.join('\n');
    expect(text).toContain('VERIFIED');
    expect(text).toContain(FIXTURE_KEY_ID);
    expect(text).toContain('pinned via --expect-key');
  });

  it('rejects the fixture by default: its key_id is not on the published trust list (exit 1)', async () => {
    const file = writeDoc(fixtureDoc());
    const { io, err } = captureIo();

    const code = await runReportSignVerify(file, {}, io);

    expect(code).toBe(1);
    const text = err.join('\n');
    expect(text).toContain('untrusted-key-id');
    expect(text).toContain(FIXTURE_KEY_ID);
  });

  it('verifies when the key_id is on the (injected) trust list and labels it published (exit 0)', async () => {
    const file = writeDoc(fixtureDoc());
    const { io, out } = captureIo();

    const code = await runReportSignVerify(file, { trustedKeyIds: [FIXTURE_KEY_ID] }, io);

    expect(code).toBe(0);
    expect(out.join('\n')).toContain('published trust list');
  });

  it('fails a tampered report body with exit 1 and a hash-mismatch reason', async () => {
    const doc = fixtureDoc();
    (doc['findings'] as Array<Record<string, unknown>>)[0]!['severity'] = 'info';
    const file = writeDoc(doc);
    const { io, err } = captureIo();

    const code = await runReportSignVerify(file, { trustedKeyIds: [FIXTURE_KEY_ID] }, io);

    expect(code).toBe(1);
    expect(err.join('\n')).toContain('hash-mismatch');
  });

  it('emits machine-readable output with --json', async () => {
    const file = writeDoc(fixtureDoc());
    const { io, out } = captureIo();

    const code = await runReportSignVerify(
      file,
      { json: true, trustedKeyIds: [FIXTURE_KEY_ID] },
      io
    );

    expect(code).toBe(0);
    const parsed = JSON.parse(out.join('\n')) as Record<string, unknown>;
    expect(parsed['ok']).toBe(true);
    expect(parsed['status']).toBe('verified-issuer');
    expect(parsed['keyId']).toBe(FIXTURE_KEY_ID);
  });

  it('reports hash-only for an unsigned v2 report (exit 0, plainly labelled)', async () => {
    const doc = fixtureDoc();
    const { integrity: _integrity, ...body } = doc;
    const sha = computeAuditHashV2(body as Record<string, unknown>) as string;
    const file = writeDoc({
      ...body,
      integrity: { sha256: sha, signature_scheme: 'none', unsigned_reason: 'no_issuer_key' },
    });
    const { io, out } = captureIo();

    const code = await runReportSignVerify(file, {}, io);

    expect(code).toBe(0);
    const text = out.join('\n');
    expect(text).toContain('HASH VERIFIED (no issuer signature)');
    expect(text).toContain('no_issuer_key');
  });

  it('fails --expect-key against an unsigned report (exit 1)', async () => {
    const doc = fixtureDoc();
    const { integrity: _integrity, ...body } = doc;
    const sha = computeAuditHashV2(body as Record<string, unknown>) as string;
    const file = writeDoc({
      ...body,
      integrity: { sha256: sha, signature_scheme: 'none', unsigned_reason: 'disabled' },
    });
    const { io, err } = captureIo();

    const code = await runReportSignVerify(file, { expectKey: PUBLISHED_KEY_ID }, io);

    expect(code).toBe(1);
    expect(err.join('\n')).toContain('expected-key-but-not-issuer-signed');
  });

  it('points guard evidence packs to the right tool instead of a generic failure', async () => {
    const file = writeDoc({ kind: 'panguard.evidence-pack', version: '1.2', attestation: {} });
    const { io, err } = captureIo();

    const code = await runReportSignVerify(file, {}, io);

    expect(code).toBe(1);
    expect(err.join('\n')).toContain('evidence pack');
  });

  it('exits 2 on a missing file', async () => {
    const { io } = captureIo();
    expect(await runReportSignVerify(join(dir, 'nope.json'), {}, io)).toBe(2);
  });

  it('exits 2 on malformed JSON', async () => {
    const file = join(dir, 'bad.json');
    writeFileSync(file, '{ not json');
    const { io } = captureIo();
    expect(await runReportSignVerify(file, {}, io)).toBe(2);
  });

  it('exits 2 on a non-object top level', async () => {
    const file = join(dir, 'arr.json');
    writeFileSync(file, '[1,2,3]');
    const { io } = captureIo();
    expect(await runReportSignVerify(file, {}, io)).toBe(2);
  });

  describe('commander wiring', () => {
    it('registers report > sign > verify and NO public signing action', () => {
      const cmd = reportCommand();
      expect(cmd.name()).toBe('report');
      const sign = cmd.commands.find((c) => c.name() === 'sign');
      expect(sign).toBeDefined();
      expect(sign?.commands.find((c) => c.name() === 'verify')).toBeDefined();
      // Issuing lives in the enterprise tooling; the free CLI must not grow a
      // competing signer.
      expect(sign?.commands.find((c) => c.name() === 'hash')).toBeUndefined();
      expect(sign?.commands.find((c) => c.name() === 'issue')).toBeUndefined();
      expect(sign?.commands.find((c) => c.name() === 'keygen')).toBeUndefined();
    });

    it('exposes the exact trust-page syntax: report sign verify <file> --expect-key <id>', async () => {
      const file = writeDoc(fixtureDoc());
      const prevExit = process.exitCode;
      const cmd = reportCommand();
      await cmd.parseAsync(['sign', 'verify', file, '--expect-key', FIXTURE_KEY_ID], {
        from: 'user',
      });
      expect(process.exitCode ?? 0).toBe(0);
      process.exitCode = prevExit;
    });
  });
});
