/**
 * Canonical JSON for audit-report hashing.
 * 稽核報告雜湊用的正規化 JSON。
 *
 * PARITY-CRITICAL: this is a verbatim-semantics port of the private issuer
 * tooling's canonicalize (@panguard/migrator audit/audit-report.ts). The
 * issuer computes integrity.sha256 with that function; this public copy must
 * produce byte-identical output for every JSON-parsed report body, or offline
 * verification breaks. Cross-repo parity is pinned by
 * tests/fixtures/issuer-signed-report.fixture.json (generated by running the
 * private issuer code itself).
 *
 * Form: recursive key-sorted JSON — object keys sorted at every depth,
 * undefined-valued keys dropped, arrays in order. Do not "improve" this
 * independently of the issuer side.
 */
export function canonicalizeAudit(value: unknown): string {
  if (value === null || typeof value !== 'object') return JSON.stringify(value);
  if (Array.isArray(value)) return `[${value.map(canonicalizeAudit).join(',')}]`;
  const record = value as Record<string, unknown>;
  const parts = Object.keys(record)
    .sort()
    .filter((k) => record[k] !== undefined)
    .map((k) => `${JSON.stringify(k)}:${canonicalizeAudit(record[k])}`);
  return `{${parts.join(',')}}`;
}
